version: '3'
services:
  master:
    build: 
      context: ./crontab/master/main # 编译 dockerfile文件
      args:
        - buildno=master_v2
        - gitcommithash=cdc3b19
    image: master:v2
    depends_on:
      - etcd
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - my_network
  # worker-1:
  #   build: ./crontab/worker/main # 编译 dockerfile文件
  # worker-2:
  #   build: ./crontab/worker/main # 编译 dockerfile文件
  etcd:
    image: "bitnami/etcd" #etcd
  mongodb:
    image: "mongo"  #mongoDb

networks:
  my_network:

