version: '3'
services:
  master:
    build: 
      context: ./master # 编译 dockerfile文件
      # args:
      #   - buildno=master_v2
      #   - gitcommithash=cdc3b19
    depends_on:
      - etcd
      - mongodb
    ports: # 暴露端口信息  - "宿主机端口:容器暴露端口"
      - "8080:8080"
    networks:
      - crontab_network
    links:
      - etcd
      - mongodb
  # worker:
  #   build: ./worker # 编译 dockerfile文件
  #   deploy:
  #     mode: replicated
  #     replicas: 2   #两个worker副本
  #   depends_on:
  #     - etcd
  #     - mongodb
  #   networks:
  #     - crontab_network
  etcd:
    image: "bitnami/etcd" #etcd
    networks:
      - crontab_network
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    expose:
      - "2379"
      - "2380"
  mongodb:
    image: "mongo"  #mongoDb
    restart: always
    expose:
      - "27017"
    networks:
      - crontab_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

networks:
  crontab_network:

